# Generated by Django 4.0.2 on 2022-02-08 18:31

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('todo', '0002_alter_todo_datecompleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('OnGoing', 'On Going'), ('NotStarted', 'Not Started'), ('Completed', 'Completed')], default='NotStarted', max_length=10),
        ),
    ]
